import "./globals.css";

export const metadata = {
  title: "Conexão Carreira",
  description: "Generated by create next app",
    icons: {
        icon: "/logo_case.png", // ou .png / .svg
    },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
